import './globals.css'
import { Inter } from 'next/font/google'
import Theme from "@/components/Theme"
import { HeaderMenu as Header } from '@/components/Header/Header'
import { createGetInitialProps } from '@mantine/next';
const inter = Inter({ subsets: ['latin'] });

// const getInitialProps = createGetInitialProps();

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  { link: "/", label: "Home" },
  { link: "/about", label: "About" },
  { link: "/balaa", label: "Balaa" }
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log(children)
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <Header links={links} />
          {children}
        </Theme>
      </body>
    </html >
  )
}
